version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: cimg/go:1.15

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /home/circleci/go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: wget https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip ; unzip terraform_0.12.29_linux_amd64.zip ; mv terraform ~/bin
      - run: cd tests ; go get -v -t -d ./...
      - run: cd tests ; go test -v ./...
